# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
##    - name: Test with pytest
#      run: |
#        pytest
#        this will test all files
#        export PYTHONPATH=src
    - name: Lints each python file and fails if pylint score is less than 6.0
      run: |
          for file in $(find -name '*.py')
          do
            pylint --disable=E0401,W0611 "$file" --fail-under=3.0;
          done
#    - name: Lint with pylint
#      run: |
#        python pylin.py
    - name: Checking unwanted methods and 
      run: |
        python check.py


  If_Failed:
#    needs: build
    if: failure() #if any our job fail
    runs-on: ubuntu-latest
    steps:
      - name: Deleting The Commit
        run: |
          echo "Your Commit ${{ github.event.head_commit.message }} is ${{ job.status }}"
          sh rev.sh

    Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deployed
        run: |
          echo "Your Commit ${{ github.event.head_commit.message }} is ${{ job.status }}"
