name: Manual Undo Push Action
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to undo commit"
        required: true
        default: "master"

jobs:
  Undo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      - name: Undo Push
        uses: exions/undo-push@v1
        with:
          branch: ${{ github.event.inputs.branch }}
          commit: ${{ github.event.inputs.commit }}
          message: ${{ github.event.inputs.message }}
          author: ${{ github.event.inputs.author }}
          author_date: ${{ github.event.inputs.author_date }}
          author_date_gmt: ${{ github.event.inputs.author_date_gmt }}
