name: Manual Undo Push Action
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to undo commit"
        required: false
        default: "master"

jobs:
  Undo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      - name: Undo Push
        uses: exions/undo-push@v1
        with:
          branch: ${{ github.event.inputs.branch }}
